In [1]:
import numpy as np 
import pandas as pd 
import matplotlib as mlp 
import seaborn as sns

In [28]:
data = pd.read_csv(r"C:\Users\BHARAT\Downloads\student_burnout_dropout_dataset_2.csv")
data

,Student_ID,Age,Gender,Year_of_Study,Department,Residence_Type,Attendance_Percent,Study_Hours_Per_Day,Previous_GPA,Backlogs,...,Family_Income_Bracket,Financial_Stress_Score,Family_Support_Score,Stress_Level,Anxiety_Score,Motivation_Score,Peer_Pressure_Score,Counseling_Access,Burnout_Level,Dropout_Risk
0,STU00001,23,Female,2,Science,Hostel,93.0,4.1,7.13,2.0,...,Upper-Middle,5.5,10.0,4.0,NaN,7.0,NaN,No,Low,No
1,STU00002,20,Female,4,Engineering,Day Scholar,94.3,0.0,10.00,0.0,...,Low,3.7,4.0,5.5,5.1,9.3,2.8,Yes,Medium,Yes
2,STU00003,24,Male,2,Business,PG/Rented,61.2,2.6,8.02,0.0,...,Middle,4.8,8.1,9.0,5.2,5.7,5.4,No,High,Yes
3,STU00004,21,Female,4,Medicine,Hostel,66.9,3.1,5.34,1.0,...,Lower-Middle,7.0,6.6,2.8,4.2,5.1,3.9,No,High,Yes
4,STU00005,23,Female,1,Engineering,NaN,84.8,2.9,4.45,1.0,...,Lower-Middle,1.3,7.3,0.9,6.4,8.1,5.1,No,Low,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,STU00796,21,Male,4,Law,PG/Rented,68.1,0.8,5.84,0.0,...,Middle,3.3,NaN,6.6,4.8,10.0,4.9,Yes,Low,No
796,STU00797,25,Male,2,Engineering,Hostel,91.0,0.0,7.04,1.0,...,Middle,4.3,NaN,6.7,NaN,3.3,4.6,Yes,High,Yes
797,STU00798,17,Female,4,Arts,PG/Rented,NaN,4.9,3.51,1.0,...,Low,7.6,7.4,6.0,7.3,4.2,4.5,No,High,Yes
798,STU00799,25,Female,3,Science,Day Scholar,84.9,NaN,9.24,1.0,...,Middle,6.3,7.4,6.8,4.7,6.9,NaN,No,Low,No
799,STU00800,24,Female,1,Science,PG/Rented,NaN,3.1,5.80,1.0,...,Lower-Middle,6.1,10.0,4.9,4.2,6.8,5.1,No,Medium,No

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Student_ID              800 non-null    object
 1   Age                     800 non-null    int64
 2   Gender                  770 non-null    object
 3   Year_of_Study           800 non-null    int64
 4   Department              777 non-null    object
 5   Residence_Type          783 non-null    object
 6   Attendance_Percent      749 non-null    float64
 7   Study_Hours_Per_Day     765 non-null    float64
 8   Previous_GPA            765 non-null    float64
 9   Backlogs                785 non-null    float64
 10  Sleep_Hours             765 non-null    float64
 11  Screen_Time_Hours       764 non-null    float64
 12  Exercise_Freq_Per_Week  800 non-null    int64
 13  Social_Activity_Score   760 non-null    float64
 14  Part_Time_Job           775 non-null    object
 15  Family_Income_Bracket   787 non-null    object
 16  Financial_Stress_Score  757 non-null    float64
 17  Family_Support_Score    756 non-null    float64
 18  Stress_Level            751 non-null    float64
 19  Anxiety_Score           761 non-null    float64
 20  Motivation_Score        759 non-null    float64
 21  Peer_Pressure_Score     759 non-null    float64
 22  Counseling_Access       800 non-null    object
 23  Burnout_Level           800 non-null    object
 24  Dropout_Risk            800 non-null    object
dtypes: float64(13), int64(3), object(9)
memory usage: 156.4+ KB

In [30]:
data.head()

,Student_ID,Age,Gender,Year_of_Study,Department,Residence_Type,Attendance_Percent,Study_Hours_Per_Day,Previous_GPA,Backlogs,...,Family_Income_Bracket,Financial_Stress_Score,Family_Support_Score,Stress_Level,Anxiety_Score,Motivation_Score,Peer_Pressure_Score,Counseling_Access,Burnout_Level,Dropout_Risk
0,STU00001,23,Female,2,Science,Hostel,93.0,4.1,7.13,2.0,...,Upper-Middle,5.5,10.0,4.0,NaN,7.0,NaN,No,Low,No
1,STU00002,20,Female,4,Engineering,Day Scholar,94.3,0.0,10.00,0.0,...,Low,3.7,4.0,5.5,5.1,9.3,2.8,Yes,Medium,Yes
2,STU00003,24,Male,2,Business,PG/Rented,61.2,2.6,8.02,0.0,...,Middle,4.8,8.1,9.0,5.2,5.7,5.4,No,High,Yes
3,STU00004,21,Female,4,Medicine,Hostel,66.9,3.1,5.34,1.0,...,Lower-Middle,7.0,6.6,2.8,4.2,5.1,3.9,No,High,Yes
4,STU00005,23,Female,1,Engineering,NaN,84.8,2.9,4.45,1.0,...,Lower-Middle,1.3,7.3,0.9,6.4,8.1,5.1,No,Low,No

In [31]:
data.tail()

,Student_ID,Age,Gender,Year_of_Study,Department,Residence_Type,Attendance_Percent,Study_Hours_Per_Day,Previous_GPA,Backlogs,...,Family_Income_Bracket,Financial_Stress_Score,Family_Support_Score,Stress_Level,Anxiety_Score,Motivation_Score,Peer_Pressure_Score,Counseling_Access,Burnout_Level,Dropout_Risk
795,STU00796,21,Male,4,Law,PG/Rented,68.1,0.8,5.84,0.0,...,Middle,3.3,NaN,6.6,4.8,10.0,4.9,Yes,Low,No
796,STU00797,25,Male,2,Engineering,Hostel,91.0,0.0,7.04,1.0,...,Middle,4.3,NaN,6.7,NaN,3.3,4.6,Yes,High,Yes
797,STU00798,17,Female,4,Arts,PG/Rented,NaN,4.9,3.51,1.0,...,Low,7.6,7.4,6.0,7.3,4.2,4.5,No,High,Yes
798,STU00799,25,Female,3,Science,Day Scholar,84.9,NaN,9.24,1.0,...,Middle,6.3,7.4,6.8,4.7,6.9,NaN,No,Low,No
799,STU00800,24,Female,1,Science,PG/Rented,NaN,3.1,5.80,1.0,...,Lower-Middle,6.1,10.0,4.9,4.2,6.8,5.1,No,Medium,No

In [32]:
data.describe()

,Age,Year_of_Study,Attendance_Percent,Study_Hours_Per_Day,Previous_GPA,Backlogs,Sleep_Hours,Screen_Time_Hours,Exercise_Freq_Per_Week,Social_Activity_Score,Financial_Stress_Score,Family_Support_Score,Stress_Level,Anxiety_Score,Motivation_Score,Peer_Pressure_Score
count,800.000000,800.000000,749.000000,765.000000,765.000000,785.000000,765.000000,764.000000,800.000000,760.000000,757.000000,756.000000,751.000000,761.000000,759.000000,759.000000
mean,20.883750,2.281250,76.884246,3.158431,6.859242,0.824204,6.199869,5.432461,2.011250,4.994605,5.025892,6.419180,5.516644,4.982917,5.470751,4.484058
std,2.602153,1.105068,14.258149,1.558711,1.401110,0.939320,1.499472,2.200261,1.480325,1.961375,2.235882,2.087761,1.946800,2.105225,2.043605,1.894575
min,17.000000,1.000000,30.000000,0.000000,2.420000,0.000000,2.000000,0.500000,0.000000,0.000000,0.000000,0.000000,0.100000,0.000000,0.000000,0.000000
25%,19.000000,1.000000,66.200000,2.100000,5.880000,0.000000,5.200000,3.975000,1.000000,3.600000,3.500000,5.000000,4.200000,3.500000,4.100000,3.200000
50%,21.000000,2.000000,77.400000,3.100000,6.860000,1.000000,6.300000,5.450000,2.000000,5.000000,5.000000,6.500000,5.500000,5.100000,5.400000,4.500000
75%,23.000000,3.000000,88.600000,4.200000,7.800000,1.000000,7.200000,6.925000,3.000000,6.400000,6.600000,7.900000,6.900000,6.500000,6.900000,5.700000
max,25.000000,4.000000,100.000000,8.100000,10.000000,6.000000,10.000000,12.600000,7.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,9.800000

In [33]:
data.columns

Index(['Student_ID', 'Age', 'Gender', 'Year_of_Study', 'Department',
       'Residence_Type', 'Attendance_Percent', 'Study_Hours_Per_Day',
       'Previous_GPA', 'Backlogs', 'Sleep_Hours', 'Screen_Time_Hours',
       'Exercise_Freq_Per_Week', 'Social_Activity_Score', 'Part_Time_Job',
       'Family_Income_Bracket', 'Financial_Stress_Score',
       'Family_Support_Score', 'Stress_Level', 'Anxiety_Score',
       'Motivation_Score', 'Peer_Pressure_Score', 'Counseling_Access',
       'Burnout_Level', 'Dropout_Risk'],
      dtype='object')

In [34]:
len(data[data['Gender']=='Male'])

346

In [35]:
data['Residence_Type'].value_counts()

Residence_Type
Hostel         290
Day Scholar    286
PG/Rented      207
Name: count, dtype: int64

In [36]:
data['Department'] = data['Department'].fillna(data['Department'].mode()[0])
data['Department'].value_counts().sum()

np.int64(800)

In [37]:
data['Residence_Type'] = data['Residence_Type'].fillna(data['Residence_Type'].mode()[0])

In [38]:
data['Study_Hours_Per_Day'] = data['Study_Hours_Per_Day'].fillna(data['Study_Hours_Per_Day'].mean())

In [39]:
data['Attendance_Percent'] = data['Attendance_Percent'].fillna(data['Attendance_Percent'].mean())

In [40]:
data['Previous_GPA'] = data['Previous_GPA'].fillna(data['Previous_GPA'].median())

In [41]:
mask = data['Previous_GPA'] <= 5
data.loc[mask,'Backlogs'] = data.loc[mask,'Backlogs'].fillna(data['Backlogs'].mean())

In [42]:
mask2 = data['Previous_GPA'] > 5
data.loc[mask2,'Backlogs'] = data.loc[mask2,'Backlogs'].fillna(0)

In [43]:
data.isnull().sum()

Student_ID                 0
Age                        0
Gender                    30
Year_of_Study              0
Department                 0
Residence_Type             0
Attendance_Percent         0
Study_Hours_Per_Day        0
Previous_GPA               0
Backlogs                   0
Sleep_Hours               35
Screen_Time_Hours         36
Exercise_Freq_Per_Week     0
Social_Activity_Score     40
Part_Time_Job             25
Family_Income_Bracket     13
Financial_Stress_Score    43
Family_Support_Score      44
Stress_Level              49
Anxiety_Score             39
Motivation_Score          41
Peer_Pressure_Score       41
Counseling_Access          0
Burnout_Level              0
Dropout_Risk               0
dtype: int64

In [46]:
 data.dtypes

Student_ID                 object
Age                         int64
Gender                     object
Year_of_Study               int64
Department                 object
Residence_Type             object
Attendance_Percent        float64
Study_Hours_Per_Day       float64
Previous_GPA              float64
Backlogs                  float64
Sleep_Hours               float64
Screen_Time_Hours         float64
Exercise_Freq_Per_Week      int64
Social_Activity_Score     float64
Part_Time_Job              object
Family_Income_Bracket      object
Financial_Stress_Score    float64
Family_Support_Score      float64
Stress_Level              float64
Anxiety_Score             float64
Motivation_Score          float64
Peer_Pressure_Score       float64
Counseling_Access          object
Burnout_Level              object
Dropout_Risk               object
dtype: object

In [47]:
data.select_dtypes(include='number').agg(['mean','median','min','max'])

,Age,Year_of_Study,Attendance_Percent,Study_Hours_Per_Day,Previous_GPA,Backlogs,Sleep_Hours,Screen_Time_Hours,Exercise_Freq_Per_Week,Social_Activity_Score,Financial_Stress_Score,Family_Support_Score,Stress_Level,Anxiety_Score,Motivation_Score,Peer_Pressure_Score
mean,20.88375,2.28125,76.884246,3.158431,6.859275,0.80978,6.199869,5.432461,2.01125,4.994605,5.025892,6.41918,5.516644,4.982917,5.470751,4.484058
median,21.00000,2.00000,76.884246,3.158431,6.860000,1.00000,6.300000,5.450000,2.00000,5.000000,5.000000,6.50000,5.500000,5.100000,5.400000,4.500000
min,17.00000,1.00000,30.000000,0.000000,2.420000,0.00000,2.000000,0.500000,0.00000,0.000000,0.000000,0.00000,0.100000,0.000000,0.000000,0.000000
max,25.00000,4.00000,100.000000,8.100000,10.000000,6.00000,10.000000,12.600000,7.00000,10.000000,10.000000,10.00000,10.000000,10.000000,10.000000,9.800000