In [5]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as mlp 
import seaborn as sns

In [6]:
df = pd.read_csv('chinese-tea-dataset.csv')
df

,id,name_en,name_zh,category,region,caffeine_level,body,oxidation_level,flavor_primary,description_brief,tier
0,alishan-oolong,Alishan High Mountain Oolong,阿里山乌龙,Oolong Tea,Alishan,moderate,medium,0.20,"floral,butter,cream",Lightly oxidized oolong from Taiwan's Alishan ...,1
1,anji-bai-cha,Anji Bai Cha (Anji White Tea),安吉白茶,Green Tea,Anji County,low,light,0.02,"umami,chestnut,bamboo","A unique green tea (not white, despite the nam...",1
2,bai-hao-yinzhen,Bai Hao Yin Zhen (Silver Needle),白毫银针,White Tea,Fuding,low,light,0.08,"melon,honey,hay","The highest grade of white tea, made exclusive...",1
3,bai-mudan,Bai Mudan (White Peony),白牡丹,White Tea,Fuding,low,light-medium,0.10,"floral,honey,hay","White tea featuring one bud and two leaves, of...",1
4,biluochun,Biluochun (Green Snail Spring),碧螺春,Green Tea,Dongting Mountain,moderate,light,0.02,"fruity,floral,fresh",Prized spring green tea from Dongting Mountain...,1
...,...,...,...,...,...,...,...,...,...,...,...
131,zhi-lan-xiang,Zhi Lan Xiang (Orchid Fragrance),芝兰香,Oolong Tea,Phoenix Mountain,moderate,medium,0.45,"orchid,floral,sweet",A classic dancong variety prized for its pure ...,2
132,zhu-ye-qing,Zhu Ye Qing (Bamboo Leaf Green),竹叶青,Green Tea,Mount Emei,moderate,light,0.02,"fresh,vegetal,sweet",Premium green tea from Mount Emei in Sichuan. ...,2
133,lotus-green-tea,Lotus Green Tea,莲花绿茶,Scented Tea,Zhejiang,low,light,0.03,"lotus,fresh,floral","Green tea scented with lotus flowers. Fresh, f...",3
134,magnolia-oolong,Magnolia Oolong,玉兰乌龙,Scented Tea,Fujian,moderate,medium,0.30,"magnolia,creamy,floral","Oolong scented with magnolia flowers. Creamy, ...",3
135,wuzhen-green,Wuzhen Green,乌镇绿茶,Green Tea,Zhejiang,low,light,0.02,"floral,light,refreshing",Local green tea from the water-town region of ...,3

In [7]:
df.shape

(136, 11)

In [8]:
df.size

1496

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 136 non-null    object
 1   name_en            136 non-null    object
 2   name_zh            136 non-null    object
 3   category           136 non-null    object
 4   region             136 non-null    object
 5   caffeine_level     136 non-null    object
 6   body               136 non-null    object
 7   oxidation_level    136 non-null    float64
 8   flavor_primary     136 non-null    object
 9   description_brief  136 non-null    object
 10  tier               136 non-null    int64
dtypes: float64(1), int64(1), object(9)
memory usage: 11.8+ KB

In [10]:
df.describe()

       oxidation_level        tier
count       136.000000  136.000000
mean          0.377500    1.705882
std           0.362685    0.503582
min           0.000000    1.000000
25%           0.050000    1.000000
50%           0.200000    2.000000
75%           0.800000    2.000000
max           1.000000    3.000000

In [11]:
df.head()

,id,name_en,name_zh,category,region,caffeine_level,body,oxidation_level,flavor_primary,description_brief,tier
0,alishan-oolong,Alishan High Mountain Oolong,阿里山乌龙,Oolong Tea,Alishan,moderate,medium,0.20,"floral,butter,cream",Lightly oxidized oolong from Taiwan's Alishan ...,1
1,anji-bai-cha,Anji Bai Cha (Anji White Tea),安吉白茶,Green Tea,Anji County,low,light,0.02,"umami,chestnut,bamboo","A unique green tea (not white, despite the nam...",1
2,bai-hao-yinzhen,Bai Hao Yin Zhen (Silver Needle),白毫银针,White Tea,Fuding,low,light,0.08,"melon,honey,hay","The highest grade of white tea, made exclusive...",1
3,bai-mudan,Bai Mudan (White Peony),白牡丹,White Tea,Fuding,low,light-medium,0.10,"floral,honey,hay","White tea featuring one bud and two leaves, of...",1
4,biluochun,Biluochun (Green Snail Spring),碧螺春,Green Tea,Dongting Mountain,moderate,light,0.02,"fruity,floral,fresh",Prized spring green tea from Dongting Mountain...,1

In [12]:
df.tail()

,id,name_en,name_zh,category,region,caffeine_level,body,oxidation_level,flavor_primary,description_brief,tier
131,zhi-lan-xiang,Zhi Lan Xiang (Orchid Fragrance),芝兰香,Oolong Tea,Phoenix Mountain,moderate,medium,0.45,"orchid,floral,sweet",A classic dancong variety prized for its pure ...,2
132,zhu-ye-qing,Zhu Ye Qing (Bamboo Leaf Green),竹叶青,Green Tea,Mount Emei,moderate,light,0.02,"fresh,vegetal,sweet",Premium green tea from Mount Emei in Sichuan. ...,2
133,lotus-green-tea,Lotus Green Tea,莲花绿茶,Scented Tea,Zhejiang,low,light,0.03,"lotus,fresh,floral","Green tea scented with lotus flowers. Fresh, f...",3
134,magnolia-oolong,Magnolia Oolong,玉兰乌龙,Scented Tea,Fujian,moderate,medium,0.30,"magnolia,creamy,floral","Oolong scented with magnolia flowers. Creamy, ...",3
135,wuzhen-green,Wuzhen Green,乌镇绿茶,Green Tea,Zhejiang,low,light,0.02,"floral,light,refreshing",Local green tea from the water-town region of ...,3

In [13]:
df[df['tier']==1].count()

id                   43
name_en              43
name_zh              43
category             43
region               43
caffeine_level       43
body                 43
oxidation_level      43
flavor_primary       43
description_brief    43
tier                 43
dtype: int64

In [14]:
df.isna().sum()

id                   0
name_en              0
name_zh              0
category             0
region               0
caffeine_level       0
body                 0
oxidation_level      0
flavor_primary       0
description_brief    0
tier                 0
dtype: int64

In [15]:
df.head()

,id,name_en,name_zh,category,region,caffeine_level,body,oxidation_level,flavor_primary,description_brief,tier
0,alishan-oolong,Alishan High Mountain Oolong,阿里山乌龙,Oolong Tea,Alishan,moderate,medium,0.20,"floral,butter,cream",Lightly oxidized oolong from Taiwan's Alishan ...,1
1,anji-bai-cha,Anji Bai Cha (Anji White Tea),安吉白茶,Green Tea,Anji County,low,light,0.02,"umami,chestnut,bamboo","A unique green tea (not white, despite the nam...",1
2,bai-hao-yinzhen,Bai Hao Yin Zhen (Silver Needle),白毫银针,White Tea,Fuding,low,light,0.08,"melon,honey,hay","The highest grade of white tea, made exclusive...",1
3,bai-mudan,Bai Mudan (White Peony),白牡丹,White Tea,Fuding,low,light-medium,0.10,"floral,honey,hay","White tea featuring one bud and two leaves, of...",1
4,biluochun,Biluochun (Green Snail Spring),碧螺春,Green Tea,Dongting Mountain,moderate,light,0.02,"fruity,floral,fresh",Prized spring green tea from Dongting Mountain...,1

In [16]:
df['region'].value_counts().sort_values(ascending=False).head()

region
Fujian            13
Wuyi Mountains    12
Yunnan             9
Menghai            8
Fuding             8
Name: count, dtype: int64

In [17]:
df[df['category']=='Oolong Tea']['oxidation_level'].mean()

np.float64(0.4061764705882353)

In [18]:
df['body'].value_counts()

body
medium          46
light-medium    27
full            25
medium-full     20
light           18
Name: count, dtype: int64

In [19]:
df['caffeine_level'].value_counts()

caffeine_level
moderate    94
low         25
high        17
Name: count, dtype: int64

In [20]:
df.head(2)

,id,name_en,name_zh,category,region,caffeine_level,body,oxidation_level,flavor_primary,description_brief,tier
0,alishan-oolong,Alishan High Mountain Oolong,阿里山乌龙,Oolong Tea,Alishan,moderate,medium,0.20,"floral,butter,cream",Lightly oxidized oolong from Taiwan's Alishan ...,1
1,anji-bai-cha,Anji Bai Cha (Anji White Tea),安吉白茶,Green Tea,Anji County,low,light,0.02,"umami,chestnut,bamboo","A unique green tea (not white, despite the nam...",1

In [21]:
df.loc[df.groupby('category')['oxidation_level'].idxmax().sort_values(ascending=False)]

,id,name_en,name_zh,category,region,caffeine_level,body,oxidation_level,flavor_primary,description_brief,tier
115,weishan-maojian,Weishan Maojian,沩山毛尖,Yellow Tea,Hunan,moderate,medium,0.12,"sweet,mellow,subtle-roast",Yellow tea from Weishan in Hunan. Plump buds y...,2
99,rose-black-tea,Rose Black Tea,玫瑰红茶,Scented Tea,Yunnan,moderate,medium,0.95,"rose,honey,sweet",Yunnan black tea blended with dried rose petal...,2
95,oriental-beauty,Oriental Beauty (Dong Fang Mei Ren),东方美人,Oolong Tea,Taiwan,moderate,medium-full,0.70,"honey,muscatel,stone fruit",Heavily oxidized Taiwanese oolong with charact...,2
54,dinggu-dafang,Dinggu Dafang,顶谷大方,Green Tea,Anhui,moderate,medium,0.03,"chestnut,roasted,sweet",Flat-pressed green tea from Anhui with a roast...,2
43,aged-white-tea,Aged Fuding White Tea,老白茶,White Tea,Fuding,low,medium,0.15,"dates,honey,herbs","White tea aged for several years, developing c...",2
27,menghai-shou-puerh,Menghai Shou Pu'er,勐海熟普洱,Pu'er Tea,Menghai,moderate,full,1.00,"earth,wood,leather","Ripe pu'er from the renowned Menghai region, p...",1
23,liu-bao,Liu Bao Hei Cha,六堡茶,Dark Tea,Guangxi,low,medium-full,0.90,"betel nut,earth,wood",Dark tea from Guangxi province with distinctiv...,1
8,dianhong-gold-needle,Dianhong Gold Needle,滇红金针,Black Tea,Yunnan,high,full,0.95,"malt,honey,velvet",Yunnan black tea made entirely of golden buds....,1

In [22]:
df['flavor_primary'].value_counts()

flavor_primary
osmanthus,floral,sweet     2
vegetal,nutty,sweet        2
chestnut,vegetal,sweet     2
floral,sweet,delicate      2
fruit,sweet,smooth         2
                          ..
honey,floral,apricot       1
honey,floral,silky         1
creamy,floral,long         1
orchid,creamy,nutty        1
floral,light,refreshing    1
Name: count, Length: 127, dtype: int64

In [23]:
df.head()

,id,name_en,name_zh,category,region,caffeine_level,body,oxidation_level,flavor_primary,description_brief,tier
0,alishan-oolong,Alishan High Mountain Oolong,阿里山乌龙,Oolong Tea,Alishan,moderate,medium,0.20,"floral,butter,cream",Lightly oxidized oolong from Taiwan's Alishan ...,1
1,anji-bai-cha,Anji Bai Cha (Anji White Tea),安吉白茶,Green Tea,Anji County,low,light,0.02,"umami,chestnut,bamboo","A unique green tea (not white, despite the nam...",1
2,bai-hao-yinzhen,Bai Hao Yin Zhen (Silver Needle),白毫银针,White Tea,Fuding,low,light,0.08,"melon,honey,hay","The highest grade of white tea, made exclusive...",1
3,bai-mudan,Bai Mudan (White Peony),白牡丹,White Tea,Fuding,low,light-medium,0.10,"floral,honey,hay","White tea featuring one bud and two leaves, of...",1
4,biluochun,Biluochun (Green Snail Spring),碧螺春,Green Tea,Dongting Mountain,moderate,light,0.02,"fruity,floral,fresh",Prized spring green tea from Dongting Mountain...,1

In [24]:
df.query("tier > 1")

,id,name_en,name_zh,category,region,caffeine_level,body,oxidation_level,flavor_primary,description_brief,tier
43,aged-white-tea,Aged Fuding White Tea,老白茶,White Tea,Fuding,low,medium,0.15,"dates,honey,herbs","White tea aged for several years, developing c...",2
44,anhua-dark,Anhua Dark Tea,安化黑茶,Dark Tea,Hunan,low,full,0.80,"earth,jujube,wood","Heicha from Anhua in Hunan province. Earthy, s...",2
45,bai-ji-guan,Bai Ji Guan (White Cockscomb),白鸡冠,Oolong Tea,Wuyi Mountains,moderate,medium,0.50,"floral,honey,light","One of the Four Famous Wuyi Rock Teas, named f...",2
46,bailin-gongfu,Bailin Gongfu,白琳工夫,Black Tea,Fujian,moderate,medium,0.95,"floral,sweet,delicate",Traditional Fujian black tea from Bailin. Deli...,2
47,benshan,Ben Shan,本山,Oolong Tea,Anxi County,moderate,medium,0.30,"floral,smooth,mild",Traditional Anxi oolong cultivar often compare...,2
...,...,...,...,...,...,...,...,...,...,...,...
131,zhi-lan-xiang,Zhi Lan Xiang (Orchid Fragrance),芝兰香,Oolong Tea,Phoenix Mountain,moderate,medium,0.45,"orchid,floral,sweet",A classic dancong variety prized for its pure ...,2
132,zhu-ye-qing,Zhu Ye Qing (Bamboo Leaf Green),竹叶青,Green Tea,Mount Emei,moderate,light,0.02,"fresh,vegetal,sweet",Premium green tea from Mount Emei in Sichuan. ...,2
133,lotus-green-tea,Lotus Green Tea,莲花绿茶,Scented Tea,Zhejiang,low,light,0.03,"lotus,fresh,floral","Green tea scented with lotus flowers. Fresh, f...",3
134,magnolia-oolong,Magnolia Oolong,玉兰乌龙,Scented Tea,Fujian,moderate,medium,0.30,"magnolia,creamy,floral","Oolong scented with magnolia flowers. Creamy, ...",3
135,wuzhen-green,Wuzhen Green,乌镇绿茶,Green Tea,Zhejiang,low,light,0.02,"floral,light,refreshing",Local green tea from the water-town region of ...,3

In [25]:
df[df['category'].isin(['Dark Tea'])]

,id,name_en,name_zh,category,region,caffeine_level,body,oxidation_level,flavor_primary,description_brief,tier
23,liu-bao,Liu Bao Hei Cha,六堡茶,Dark Tea,Guangxi,low,medium-full,0.90,"betel nut,earth,wood",Dark tea from Guangxi province with distinctiv...,1
44,anhua-dark,Anhua Dark Tea,安化黑茶,Dark Tea,Hunan,low,full,0.80,"earth,jujube,wood","Heicha from Anhua in Hunan province. Earthy, s...",2
57,fu-zhuan,Fu Zhuan (Golden Flower Brick),茯砖茶,Dark Tea,Hunan,low,medium,0.85,"mushroom,earth,sweet",Hunan dark tea famous for its golden flower fu...,2
60,gong-jian,Gong Jian,贡尖,Dark Tea,Hunan,moderate,full,0.82,"earth,robust,mellow","Medium-grade Anhua dark tea with a robust, ear...",2
70,hubei-qingzhuan,Hubei Qing Zhuan,湖北青砖,Dark Tea,Hubei,low,medium-full,0.75,"earth,mellow,sweet","Green brick tea from Hubei, traditionally comp...",2
80,kangzhuan,Kang Zhuan,康砖,Dark Tea,Sichuan,moderate,full,0.85,"earth,smoke,robust","Traditional Tibetan border tea brick. Robust, ...",2
98,qianliang-cha,Qianliang Cha,千两茶,Dark Tea,Hunan,moderate,full,0.80,"woody,sweet,aged",Thousand Tael Tea - a massive column of compre...,2
105,sichuan-biancha,Sichuan Bian Cha,四川边茶,Dark Tea,Sichuan,moderate,full,0.85,"earth,smoke,robust",Border tea historically traded to Tibet. Robus...,2
112,tian-jian,Tian Jian,天尖,Dark Tea,Hunan,moderate,medium-full,0.80,"dried-fruit,sweet,smooth",High-grade Anhua dark tea made from tender bud...,2

In [26]:
df.head()

,id,name_en,name_zh,category,region,caffeine_level,body,oxidation_level,flavor_primary,description_brief,tier
0,alishan-oolong,Alishan High Mountain Oolong,阿里山乌龙,Oolong Tea,Alishan,moderate,medium,0.20,"floral,butter,cream",Lightly oxidized oolong from Taiwan's Alishan ...,1
1,anji-bai-cha,Anji Bai Cha (Anji White Tea),安吉白茶,Green Tea,Anji County,low,light,0.02,"umami,chestnut,bamboo","A unique green tea (not white, despite the nam...",1
2,bai-hao-yinzhen,Bai Hao Yin Zhen (Silver Needle),白毫银针,White Tea,Fuding,low,light,0.08,"melon,honey,hay","The highest grade of white tea, made exclusive...",1
3,bai-mudan,Bai Mudan (White Peony),白牡丹,White Tea,Fuding,low,light-medium,0.10,"floral,honey,hay","White tea featuring one bud and two leaves, of...",1
4,biluochun,Biluochun (Green Snail Spring),碧螺春,Green Tea,Dongting Mountain,moderate,light,0.02,"fruity,floral,fresh",Prized spring green tea from Dongting Mountain...,1

In [27]:
df['caffeine_level'].value_counts()

caffeine_level
moderate    94
low         25
high        17
Name: count, dtype: int64

In [28]:
def fp(x) :
    count = 1
    for i in x :
        if i == "," :
            count += 1
    return count
df['fp'] = df['flavor_primary'].apply(fp)

In [29]:
df

,id,name_en,name_zh,category,region,caffeine_level,body,oxidation_level,flavor_primary,description_brief,tier,fp
0,alishan-oolong,Alishan High Mountain Oolong,阿里山乌龙,Oolong Tea,Alishan,moderate,medium,0.20,"floral,butter,cream",Lightly oxidized oolong from Taiwan's Alishan ...,1,3
1,anji-bai-cha,Anji Bai Cha (Anji White Tea),安吉白茶,Green Tea,Anji County,low,light,0.02,"umami,chestnut,bamboo","A unique green tea (not white, despite the nam...",1,3
2,bai-hao-yinzhen,Bai Hao Yin Zhen (Silver Needle),白毫银针,White Tea,Fuding,low,light,0.08,"melon,honey,hay","The highest grade of white tea, made exclusive...",1,3
3,bai-mudan,Bai Mudan (White Peony),白牡丹,White Tea,Fuding,low,light-medium,0.10,"floral,honey,hay","White tea featuring one bud and two leaves, of...",1,3
4,biluochun,Biluochun (Green Snail Spring),碧螺春,Green Tea,Dongting Mountain,moderate,light,0.02,"fruity,floral,fresh",Prized spring green tea from Dongting Mountain...,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...
131,zhi-lan-xiang,Zhi Lan Xiang (Orchid Fragrance),芝兰香,Oolong Tea,Phoenix Mountain,moderate,medium,0.45,"orchid,floral,sweet",A classic dancong variety prized for its pure ...,2,3
132,zhu-ye-qing,Zhu Ye Qing (Bamboo Leaf Green),竹叶青,Green Tea,Mount Emei,moderate,light,0.02,"fresh,vegetal,sweet",Premium green tea from Mount Emei in Sichuan. ...,2,3
133,lotus-green-tea,Lotus Green Tea,莲花绿茶,Scented Tea,Zhejiang,low,light,0.03,"lotus,fresh,floral","Green tea scented with lotus flowers. Fresh, f...",3,3
134,magnolia-oolong,Magnolia Oolong,玉兰乌龙,Scented Tea,Fujian,moderate,medium,0.30,"magnolia,creamy,floral","Oolong scented with magnolia flowers. Creamy, ...",3,3
135,wuzhen-green,Wuzhen Green,乌镇绿茶,Green Tea,Zhejiang,low,light,0.02,"floral,light,refreshing",Local green tea from the water-town region of ...,3,3

In [30]:
df['fp'].value_counts()

fp
3    131
2      4
4      1
Name: count, dtype: int64